"""Tests for PatchGenerator."""
from __future__ import annotations

from sqlite_diffx.core.diff_engine import DiffEngine
from sqlite_diffx.core.introspector import SchemaIntrospector
from sqlite_diffx.core.patch import PatchGenerator
from sqlite_diffx.utils.db import open_db


def _schema(path):
    with open_db(path) as conn:
        return SchemaIntrospector(conn).extract()


def _patch(path1, path2):
    s1 = _schema(path1)
    s2 = _schema(path2)
    diff = DiffEngine().compare(s1, s2)
    return PatchGenerator().generate(diff, s2)


def test_header_present(simple_db, modified_db):
    patch = _patch(simple_db, modified_db)
    assert patch.startswith("-- Generated by sqlite-diffx")


def test_header_timestamp_present(simple_db, modified_db):
    patch = _patch(simple_db, modified_db)
    # Second line contains a UTC timestamp
    lines = patch.splitlines()
    assert any("T" in line and "Z" in line for line in lines[:3])


def test_empty_diff_produces_no_changes_comment(simple_db):
    patch = _patch(simple_db, simple_db)
    assert "No schema changes to apply" in patch


def test_generates_add_column_for_modified_table(simple_db, modified_db):
    patch = _patch(simple_db, modified_db)
    assert 'ALTER TABLE "users" ADD COLUMN "age" INTEGER' in patch


def test_generates_create_table_for_added_table(simple_db, extra_table_db):
    patch = _patch(simple_db, extra_table_db)
    assert 'CREATE TABLE IF NOT EXISTS "products"' in patch


def test_create_table_includes_all_columns(empty_db, simple_db):
    patch = _patch(empty_db, simple_db)
    assert '"id"' in patch
    assert '"name"' in patch
    assert '"email"' in patch


def test_create_table_single_pk_inline(empty_db, simple_db):
    patch = _patch(empty_db, simple_db)
    assert "PRIMARY KEY" in patch


def test_create_table_composite_pk(make_db, empty_db):
    db2 = make_db(
        "multi_pk.db",
        {
            "order_items": (
                "CREATE TABLE order_items ("
                "order_id INTEGER, item_id INTEGER, qty INTEGER, "
                "PRIMARY KEY (order_id, item_id))"
            )
        },
    )
    patch = _patch(empty_db, db2)
    assert "PRIMARY KEY" in patch
    assert '"order_id"' in patch
    assert '"item_id"' in patch


def test_no_drop_statements_for_removed_table(extra_table_db, simple_db):
    patch = _patch(extra_table_db, simple_db)
    # Actual DROP statement must not appear (only in comments)
    lines = [l for l in patch.splitlines() if not l.strip().startswith("--")]
    assert not any("DROP TABLE" in line for line in lines)


def test_no_drop_column_statement(modified_db, simple_db):
    patch = _patch(modified_db, simple_db)
    lines = [l for l in patch.splitlines() if not l.strip().startswith("--")]
    assert not any("DROP COLUMN" in line for line in lines)


def test_removed_table_warning_comment_present(extra_table_db, simple_db):
    patch = _patch(extra_table_db, simple_db)
    assert "WARNING" in patch
    assert "products" in patch


def test_not_null_column_in_alter(make_db, empty_db):
    db2 = make_db("nn.db", {"t": [("id", "INTEGER", "PRIMARY KEY"), ("val", "TEXT", "NOT NULL")]})
    db1 = make_db("nn_old.db", {"t": [("id", "INTEGER", "PRIMARY KEY")]})
    patch = _patch(db1, db2)
    assert "NOT NULL" in patch


def test_default_value_in_alter(make_db):
    db1 = make_db("d1.db", {"t": [("id", "INTEGER", "PRIMARY KEY")]})
    db2 = make_db("d2.db", {"t": [("id", "INTEGER", "PRIMARY KEY"), ("status", "TEXT", "DEFAULT", "'active'")]})
    patch = _patch(db1, db2)
    assert "DEFAULT" in patch
    assert "'active'" in patch
