"""
patch.py — Forward-only SQL patch generator.

Generates a safe, executable SQL migration from an old schema to a new one.
NEVER generates DROP TABLE or DROP COLUMN — those are too destructive to
include by default. Removed objects are emitted as commented-out warnings.
"""
from __future__ import annotations

from datetime import datetime, timezone

from .schema import ColumnDef, DatabaseSchema, RawDiff


class PatchGenerator:
    """
    Produces a forward-only SQL migration script from a RawDiff.

    The generator needs *schema2* (the target schema) in addition to the diff
    so it can reconstruct full CREATE TABLE statements for newly added tables.

    Usage::

        patch = PatchGenerator().generate(diff, schema2)
        print(patch)
    """

    def generate(self, diff: RawDiff, schema2: DatabaseSchema) -> str:
        """
        Return a SQL patch string.

        Always returns a non-empty string — at minimum the header comment
        plus a "no changes" note when the diff has no schema changes.
        """
        lines: list[str] = []

        # Header
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        lines.append("-- Generated by sqlite-diffx")
        lines.append(f"-- {ts}")
        lines.append("")

        schema_diff = diff.schema
        has_changes = False

        # CREATE TABLE for every added table
        for table_name in schema_diff.added_tables:
            table_def = schema2.tables[table_name]
            lines.append(self._create_table_sql(table_name, table_def.columns))
            lines.append("")
            has_changes = True

        # ALTER TABLE ADD COLUMN for every added column in modified tables
        for table_name, table_diff in schema_diff.modified_tables.items():
            for col in table_diff.added_columns:
                lines.append(self._add_column_sql(table_name, col))
                has_changes = True
            if table_diff.added_columns:
                lines.append("")

        # Warn about removals — never emit actual DROP statements
        if schema_diff.removed_tables:
            lines.append("-- WARNING: The following tables were removed from the target schema.")
            lines.append("-- DROP statements are intentionally omitted for safety.")
            lines.append("-- Review carefully before running manually:")
            for table_name in schema_diff.removed_tables:
                lines.append(f'-- DROP TABLE "{table_name}";')
            lines.append("")
            has_changes = True

        for table_name, table_diff in schema_diff.modified_tables.items():
            if table_diff.removed_columns:
                lines.append(
                    f'-- WARNING: The following columns were removed from "{table_name}".'
                )
                lines.append("-- Review carefully before running manually:")
                for col in table_diff.removed_columns:
                    lines.append(
                        f'-- ALTER TABLE "{table_name}" DROP COLUMN "{col.name}";'
                    )
                lines.append("")
                has_changes = True

        if not has_changes:
            lines.append("-- No schema changes to apply.")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _create_table_sql(
        self, table_name: str, columns: dict[str, ColumnDef]
    ) -> str:
        """Generate a CREATE TABLE IF NOT EXISTS statement with all columns."""
        # Determine PK column(s) — sorted by their pk index
        pk_entries = sorted(
            [(name, col.pk) for name, col in columns.items() if col.pk > 0],
            key=lambda x: x[1],
        )
        pk_names = [name for name, _ in pk_entries]

        col_fragments = [
            self._column_def_fragment(col, pk_names)
            for col in columns.values()
        ]

        # Composite PK: emit as table constraint instead of inline
        if len(pk_names) > 1:
            pk_list = ", ".join(f'"{n}"' for n in pk_names)
            col_fragments.append(f"PRIMARY KEY ({pk_list})")

        inner = ",\n    ".join(col_fragments)
        safe = table_name.replace('"', '""')
        return f'CREATE TABLE IF NOT EXISTS "{safe}" (\n    {inner}\n);'

    def _add_column_sql(self, table_name: str, col: ColumnDef) -> str:
        """Generate an ALTER TABLE … ADD COLUMN statement."""
        col_def = self._inline_col_def(col, include_pk=False)
        safe_table = table_name.replace('"', '""')
        return f'ALTER TABLE "{safe_table}" ADD COLUMN {col_def};'

    def _column_def_fragment(self, col: ColumnDef, pk_names: list[str]) -> str:
        """
        Build the column definition fragment for use inside CREATE TABLE.

        For single-column PKs the PRIMARY KEY keyword is inlined.
        For composite PKs it is emitted as a separate table constraint, so
        we skip the inline keyword here.
        """
        return self._inline_col_def(
            col,
            include_pk=(len(pk_names) == 1 and col.pk == 1),
        )

    def _inline_col_def(self, col: ColumnDef, include_pk: bool) -> str:
        """Build a column definition string (name + type + constraints)."""
        safe_name = col.name.replace('"', '""')
        col_type = col.type or "TEXT"

        parts = [f'"{safe_name}"', col_type]

        if include_pk:
            parts.append("PRIMARY KEY")
        elif col.notnull and col.pk == 0:
            # Don't emit NOT NULL on PK columns — SQLite forbids that combination
            parts.append("NOT NULL")

        if col.default is not None:
            parts.append(f"DEFAULT {col.default}")

        return " ".join(parts)
